language: csharp
solution: Pacman.sln

install:
  - nuget restore Pacman.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
  
script:
  - msbuild /p:Configuration=Release Pacman.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./PacmanTest.Test/bin/Release/PacmanTest.Test.dll
