language: csharp
solution: Pacman.sln

mono: latest

dotnet: 3.1

install:
  - dotnet restore
  - nuget restore Pacman.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
  
script:
  - msbuild /p:Configuration=Release Pacman.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./PacmanTest/bin/Release/PacmanTest.dll
